receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  coralogix:
    traces:
      endpoint: "CORALOGIX_ENDPOINT"
    private_key: "CORALOGIX_API_KEY
    application_name: "otel-demo"


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [coralogix]
